# Generated by Django 4.0.6 on 2022-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='revision_count',
            field=models.IntegerField(default=0),
        ),
    ]
