# Generated by Django 4.0.6 on 2022-07-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questions_revision_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='shared_url',
        ),
        migrations.AddField(
            model_name='questions',
            name='tag',
            field=models.CharField(default='DSA', max_length=500),
        ),
    ]
